//dropdown labels
export const dropdowndata = [
    //ENGINEERING BUILDING 1ST FLOOR------------------------------
    { key: '1', value: 'NEAREST MALE CR'},
    { key: '2', value: 'NEAREST FEMALE CR'},
    { key: '3', value: 'EN 101' },
    { key: '4', value: 'EN 102' },
    { key: '5', value: 'EN 103' },
    { key: '6', value: 'EN 104' }, // Trippings muna to
    { key: '7', value: 'ACCREDITATION ROOM' },
    { key: '8', value: 'ACES PICE OFFICE' },
    { key: '9', value: 'M.E. LAB'},
    { key: '10', value: 'Faculty Briefing & Training Room' },
    { key: '11', value: 'Deans Office' },
    { key: '12', value: 'Fluid Mechanics & Hydraulics Room'},
    { key: '13', value: 'COE (Deans Office)' },
    { key: '14', value: 'CE Tool Room' },
    { key: '15', value: 'Structural Material & Testing Lab' },
    { key: '16', value: 'Soil Mechanics Laboratory' },
    { key: '17', value: 'EN 112'},
    { key: '18', value: 'EN 113'},
    { key: '19', value: 'EN 111B'},
    { key: '20', value: 'ME TOOL ROOM'},
    { key: '21', value: 'CE Faculty Room'},
    { key: '22', value: 'ME Lab'},
    { key: '23', value: 'CPE Faculty Room'},
    { key: '24', value: 'ECE Faculty Room'},
    { key: '25', value: 'Machine Fabrication Room'},
    { key: '26', value: 'EE Faculty Room'},
    { key: '27', value: 'ME Faculty Room'},
    { key: '28', value: 'Electrical Room'},
    { key: '29', value: 'EN 118'},
    { key: '30', value: 'CAS Faculty Room' },
    { key: '31', value: 'EN 117'}
  ];

  //Room Coordinates
  export const buildingCoordinates = {
    //ENGINEERING BUILDING 1ST FLOOR------------------------------
    'EN 101': { x: 0.55, y: 0.93 },
    'EN 102': { x: 0.45, y: 0.93 }, 
    'EN 103': { x: 0.50, y: 0.87 }, 
    'EN 104': { x: 0.45, y: 0.82 },
    'EN 112': { x: 0.50, y: 0.50 },
    'EN 113': { x: 0.50, y: 0.43 },
    'EN 111B': { x: 0.60, y: 0.43 },
    'EN 117': { x: 0.60, y: 0.06 },
    'EN 118': { x: 0.50, y: 0.06 },
    'ACCREDITATION ROOM': { x: 0.6, y: 0.82 },
    'ACES PICE OFFICE': { x: 0.32, y: 0.94 },
    'MALE COMFORT ROOM (CR) - LEFT WING': { x: 0.24, y: 0.95 },
    'FEMALE COMFORT ROOM (CR) - LEFT WING': { x: 0.79, y: 0.96 },
    'M.E. LAB': { x: 0.50, y: 0.75 },
    'Faculty Briefing & Training Room': { x: 0.65, y: 0.75 },
    'Deans Office': { x: 0.45, y: 0.66 },
    'Fluid Mechanics & Hydraulics Room': { x: 0.63, y: 0.66 },
    'COE (Deans Office)': { x: 0.50, y: 0.60 },
    'CE Tool Room': { x: 0.60, y: 0.58 },
    'Structural Material & Testing Lab': { x: 0.60, y: 0.53 },
    'Soil Mechanics Laboratory': { x: 0.60, y: 0.48 },
    'ME TOOL ROOM': { x: 0.50, y: 0.38 },
    'CE Faculty Room': { x: 0.60, y: 0.36 },
    'ME Lab': { x: 0.50, y: 0.32 },
    'CPE Faculty Room': { x: 0.60, y: 0.32 },
    'ECE Faculty Room': { x: 0.60, y: 0.25 },
    'Machine Fabrication Room': { x: 0.50, y: 0.25 },
    'EE Faculty Room': { x: 0.60, y: 0.22 },
    'ME Faculty Room': { x: 0.60, y: 0.16 },
    'Electrical Room': { x: 0.59, y: 0.13 },
    'CAS Faculty Room': { x: 0.32, y: 0.05 },
    'MALE COMFORT ROOM (CR) - RIGHT WING': { x: 0.29, y: 0.05 },
    'FEMALE COMFORT ROOM (CR) - RIGHT WING': { x: 0.79, y: 0.06 },
    
    
    //Hallway Nodes (not actual rooms) 
    'V': { x: 0.73, y: 0.92 },
    'U': { x: 0.54, y: 0.91 },
    'T': { x: 0.34, y: 0.90 },
    'T1': { x: 0.25, y: 0.9 },

    'A': { x: 0.55, y: 0.82 },
    'B': { x: 0.55, y: 0.75 },
    'C': { x: 0.55, y: 0.66 },
    'D': { x: 0.55, y: 0.58 },
    'E': { x: 0.55, y: 0.53 },
    'F': { x: 0.55, y: 0.43 },
    'G': { x: 0.55, y: 0.38 },
    'H': { x: 0.55, y: 0.32 },
    'I': { x: 0.55, y: 0.25 },
    'J': { x: 0.55, y: 0.16 },

    'X': { x: 0.27, y: 0.08 },
    'Y': { x: 0.55, y: 0.08 },
    'Z': { x: 0.72, y: 0.08 },
    
  };

  //connections 
 export const graph = {
    //ENGINEERING BUILDING 1ST FLOOR------------------------------
    'EN 101': { 'U': 1 },
    'EN 102': { 'U': 1 },
    'EN 103': { 'U': 1 },
    'EN 104': { 'A': 1,},
    'EN 112': { 'E': 1 },
    'EN 113': { 'F': 1 },
    'EN 118': { 'Z': 1 },
    'EN 117': { 'Y': 1},
    'EN 111B': { 'F': 1},

    'ACCREDITATION ROOM': { 'A': 1,},
    'FEMALE COMFORT ROOM (CR) - LEFT WING': { 'V': 1,},
    'MALE COMFORT ROOM (CR) - LEFT WING': { 'T1': 1,},
    'ACES PICE OFFICE': { 'T': 1,},
    'M.E. LAB': { 'B': 1,},
    'Faculty Briefing & Training Room': { 'B': 1},
    'Fluid Mechanics & Hydraulics Room': { 'C': 1},
    'Deans Office': { 'C': 1},
    'COE (Deans Office)': { 'D': 1, 'C': 1},
    'CE Tool Room': { 'D': 1},
    'Structural Material & Testing Lab': { 'E': 1},
    'Soil Mechanics Laboratory': { 'E': 1},
    'ME TOOL ROOM': { 'G': 1},
    'CE Faculty Room': { 'G': 1},
    'ME Lab': { 'H': 1},
    'CPE Faculty Room': { 'H': 1},
    'ECE Faculty Room': { 'I': 1},
    'Machine Fabrication Room': { 'I': 1},
    'EE Faculty Room': { 'I': 1},
    'ME Faculty Room': { 'J': 1},
    'Electrical Room': { 'J': 1},
    'CAS Faculty Room': { 'X': 1},
    'MALE COMFORT ROOM (CR) - RIGHT WING': { 'X': 1},
    'FEMALE COMFORT ROOM (CR) - RIGHT WING': { 'Z': 1},
    
    'A': { 'EN 104': 1, 'ACCREDITATION ROOM': 1, 'U': 3, 'B': 2 },
    'B': { 'A': 2, 'Faculty Training & Briefing Room' : 1, 'C': 2},
    'C': { 'B': 2, 'D': 2,'Deans Office': 1, 'Fluid Mechanics & Hydraulics Room': 1,  'COE (Deans Office)': 1},
    'D': { 'C': 2, 'E': 2, 'COE (Deans Office)': 1, 'CE Tool Room': 1 },
    'E': { 'D': 2, 'F': 2, 'Structural Material & Testing Lab': 1, 'Soil Mechanics Laboratory': 1, 'EN 112': 1 },
    'F': { 'E': 2, 'G': 2, 'EN 113': 1 , 'EN 111B': 1},
    'G': { 'F': 2, 'H': 2, 'ME TOOL ROOM': 1, 'CE Faculty Room': 1 },
    'H': { 'G': 2, 'I': 2, 'ME Lab': 1, 'CPE Faculty Room': 1 },
    'I': { 'H': 2, 'J': 4, 'Y': 1, 'ECE Faculty Room': 1, 'Machine Fabrication Room': 1, 'EE Faculty Room': 1 },
    'J': { 'I': 2, 'Y': 1, 'ME Faculty Room': 1, 'Electrical Room': 1 },

    'T': { 'ACES PICE OFFICE': 1, 'U': 2, 'T1': 1 },
    'U': { 'EN 101': 1, 'EN 102': 1, 'EN 103': 1, 'T': 2, 'A': 3, 'V': 2 },
    'V': { 'FEMALE COMFORT ROOM (CR) - LEFT WING': 1, 'U': 2 },
    'T1': { 'T': 1, 'MALE COMFORT ROOM (CR) - LEFT WING': 1},
    
    'X': { 'CAS Faculty Room': 1, 'Y': 2, 'MALE COMFORT ROOM (CR) - RIGHT WING': 2 },
    'Y': { 'I': 2, 'X': 2, 'Z': 2, 'EN 118': 1,  'EN 117': 1  },
    'Z': { 'Y': 2, 'FEMALE COMFORT ROOM (CR) - RIGHT WING': 1},

  };